In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5, 4)
print(x)

tensor([[1.4974e-25, 4.5764e-41, 1.4974e-25, 4.5764e-41],
        [4.8617e+30, 1.5766e-19, 3.5972e-12, 1.2873e+31],
        [7.6814e+31, 9.3264e-09, 2.1707e-18, 3.0958e-18],
        [4.1473e-08, 5.1380e+31, 3.3132e-18, 1.4062e-16],
        [3.0963e-18, 5.1380e+31, 3.1095e-18, 9.8954e-03]])


In [3]:
torch.ones(3, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [4]:
torch.zeros(2)

tensor([0., 0.])

In [5]:
torch.rand(5, 6)

tensor([[0.8158, 0.3274, 0.7424, 0.2721, 0.7591, 0.2570],
        [0.6824, 0.6425, 0.9734, 0.1545, 0.2603, 0.5879],
        [0.6849, 0.5829, 0.1213, 0.0851, 0.2192, 0.1065],
        [0.2551, 0.4559, 0.3573, 0.7961, 0.3420, 0.3911],
        [0.3690, 0.8383, 0.9511, 0.7726, 0.7864, 0.1274]])

In [6]:
x = torch.rand(8, 8)

x.size(), x

(torch.Size([8, 8]),
 tensor([[0.6194, 0.3089, 0.3798, 0.0714, 0.3727, 0.8564, 0.4030, 0.8040],
         [0.3111, 0.7977, 0.2070, 0.9346, 0.7930, 0.2959, 0.9887, 0.1163],
         [0.0938, 0.0639, 0.7850, 0.1821, 0.7157, 0.0171, 0.7203, 0.4248],
         [0.8160, 0.3853, 0.0140, 0.1395, 0.1714, 0.9930, 0.5587, 0.9305],
         [0.7473, 0.6313, 0.7576, 0.4306, 0.8122, 0.1671, 0.3558, 0.1364],
         [0.7776, 0.7054, 0.1244, 0.2272, 0.2858, 0.4808, 0.4454, 0.7658],
         [0.0045, 0.2442, 0.0536, 0.7826, 0.0038, 0.3633, 0.6354, 0.4090],
         [0.7407, 0.1560, 0.9953, 0.3433, 0.6917, 0.1398, 0.4522, 0.6045]]))

In [13]:
a = x.view(2, 32)
b = x.view(64)
a, a.shape, b, b.size()

(tensor([[0.6194, 0.3089, 0.3798, 0.0714, 0.3727, 0.8564, 0.4030, 0.8040, 0.3111,
          0.7977, 0.2070, 0.9346, 0.7930, 0.2959, 0.9887, 0.1163, 0.0938, 0.0639,
          0.7850, 0.1821, 0.7157, 0.0171, 0.7203, 0.4248, 0.8160, 0.3853, 0.0140,
          0.1395, 0.1714, 0.9930, 0.5587, 0.9305],
         [0.7473, 0.6313, 0.7576, 0.4306, 0.8122, 0.1671, 0.3558, 0.1364, 0.7776,
          0.7054, 0.1244, 0.2272, 0.2858, 0.4808, 0.4454, 0.7658, 0.0045, 0.2442,
          0.0536, 0.7826, 0.0038, 0.3633, 0.6354, 0.4090, 0.7407, 0.1560, 0.9953,
          0.3433, 0.6917, 0.1398, 0.4522, 0.6045]]),
 torch.Size([2, 32]),
 tensor([0.6194, 0.3089, 0.3798, 0.0714, 0.3727, 0.8564, 0.4030, 0.8040, 0.3111,
         0.7977, 0.2070, 0.9346, 0.7930, 0.2959, 0.9887, 0.1163, 0.0938, 0.0639,
         0.7850, 0.1821, 0.7157, 0.0171, 0.7203, 0.4248, 0.8160, 0.3853, 0.0140,
         0.1395, 0.1714, 0.9930, 0.5587, 0.9305, 0.7473, 0.6313, 0.7576, 0.4306,
         0.8122, 0.1671, 0.3558, 0.1364, 0.7776, 0.7054, 0

In [14]:
b = x.view(-1, 4, 4)

b.shape

torch.Size([4, 4, 4])

In [16]:
x = torch.rand(8, 8)
y = x.numpy()

type(y)

numpy.ndarray

In [19]:
x = torch.ones(5)

x

tensor([1., 1., 1., 1., 1.])

In [20]:
x.item()

ValueError: only one element tensors can be converted to Python scalars

In [26]:
x = torch.ones(1)

x.item()

1.0