In [2]:
import torch

x = torch.ones(2, 2, requires_grad=True)

x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x + 1
z = 2 * y ** 2
res = z.mean()

y, z, res

(tensor([[2., 2.],
         [2., 2.]], grad_fn=<AddBackward0>),
 tensor([[8., 8.],
         [8., 8.]], grad_fn=<MulBackward0>),
 tensor(8., grad_fn=<MeanBackward0>))

In [4]:
res.backward()

In [5]:
print(x)
print(x.grad)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[2., 2.],
        [2., 2.]])
